CREATE DATABASE IF NOT EXISTS keeps_light;
USE keeps_light;

CREATE TABLE IF NOT EXISTS notes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    content TEXT,
    is_pinned TINYINT(1) DEFAULT 0,
    color VARCHAR(50) DEFAULT 'bg-default',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
